import Link from "next/link"
import { promises as fs } from "fs"
import path from "path"
import { AppShell } from "@/components/shell/AppShell"
import { SectionMarker } from "@/components/shell/SectionMarker"
import { Button } from "@/components/ui/button"
import { DO_NOT_MISS, MISTAKE_MUSEUM, PEARLS, TOPIC_INDEX } from "@/lib/demo/demo-content"
export const dynamic = "force-dynamic"
async function loadReview(){try{return await fs.readFile(path.join(process.cwd(),"CONTENT_REVIEW.md"),"utf-8")}catch{return ""}}
export default async function ContentReviewPage(){const text=await loadReview();const total=3+TOPIC_INDEX.length+PEARLS.length+MISTAKE_MUSEUM.length+DO_NOT_MISS.length;const counts=[["Cases",3],["Topics",TOPIC_INDEX.length],["Pearls",PEARLS.length],["Mistakes",MISTAKE_MUSEUM.length],["Do-Not-Miss",DO_NOT_MISS.length],["Unverified",total]];return <AppShell><div className="mx-auto max-w-screen-xl px-4 py-8 sm:px-6 lg:px-8"><SectionMarker number="07" label="Content Review" className="mb-3" /><h1 className="text-h1 font-fraunces text-ink">Content Review</h1><p className="mt-2 max-w-3xl text-small text-ink-muted">Local read-only review studio for Phase 0B.2. Nothing is sent to faculty yet. Faculty verification workflow is planned for Phase 0C. No PHI.</p><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3">{counts.map(([label,value])=><div key={label as string} className="rounded-2xl bg-bg-elevated p-4 ring-1 ring-rule/70 shadow-soft"><p className="text-micro uppercase tracking-wide text-ink-faint">{label as string}</p><p className="mt-1 text-h3 font-semibold text-ink">{value as number}</p><p className="text-micro text-ink-muted">needs faculty review</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2"><Button asChild variant="outline"><Link href="/case">View cases</Link></Button><Button asChild variant="outline"><Link href="/topics">View topics</Link></Button></div><section className="mt-6 rounded-2xl bg-bg-elevated p-4 ring-1 ring-rule/70 shadow-soft"><p className="text-small font-semibold text-ink">CONTENT_REVIEW.md (read-only)</p><pre className="mt-3 max-h-[55vh] overflow-auto whitespace-pre-wrap break-words text-small text-ink-muted">{text||"CONTENT_REVIEW.md not found."}</pre></section></div></AppShell>}
